# Generated by Django 5.0 on 2023-12-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
